apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  ports:
    - port: 80
  selector:
    app: httpd
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-storage-claim
  labels:
    app: httpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  labels:
    app: httpd
spec:
  selector:
    matchLabels:
      app: httpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 8080
          name: httpd
        volumeMounts:
        - name: httpd-storage
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: httpd-storage
        persistentVolumeClaim:
          claimName: httpd-storage-claim
